config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'aide'        => 'pages#aide'
  get 'contact'     => 'pages#contact'
  get 'inscription' => 'utilisateurs#new'

  resources :utilisateurs

  get 'login'  => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :utilisateur
end

app/models/utilisateur.rb
class Utilisateur < ApplicationRecord
  validates :nom, presence: true, length:  {maximum:50}


  VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL}
  validates :password, presence: true, length: {minimum: 6}
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @titre = "Home"
  end

  def aide
    @titre = "Aide"
  end

  def contact
    @titre = "Contact"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    utilisateur = Utilisateur.find_by(email: params[:session][:email].downcase)
    if utilisateur && utilisateur.authenticate(params[:session][:password])
      log_in utilisateur
      redirect_to utilisateur
    else
      flash[:danger] = 'Combinaison Email/Mot de passe invalide'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/utilisateurs_controller.rb
class UtilisateursController < ApplicationController
  before_action :authenticate, :only => [:index, :edit, :update, :destroy]
  before_action :bon_utilisateur, :only => [:edit, :update]
  def index
    @utilisateurs = Utilisateur.all
  end

  def new
    @utilisateur = Utilisateur.new
  end

  def show
    @utilisateur = Utilisateur.find(params[:id])
  end

  def create
    puts :utilisateur
    @utilisateur = Utilisateur.new(utilisateur_params)
    if @utilisateur.save
      flash[:success] = "Bienvenue!"
        redirect_to @utilisateur
    else
      render 'new'
    end
  end

  def edit
    @utilisateur = Utilisateur.find(params[:id])
  end

  def update
    @utilisateur = Utilisateur.find(params[:id])
    if @utilisateur.update(utilisateur_params)
      flash[:success] = "Profile Actualisé!"
      redirect_to @utilisateur
    else
      render 'edit'
    end
  end

  def destroy
    Utilisateur.find(params[:id]).destroy
	flash[:success] = "Utilisateur supprimé"
	redirect_to root_url
  end


  private
    def utilisateur_params
      params.require(:utilisateur).permit(:nom, :email, :password, :password_confirmation)
    end

    def authenticate
      unless logged_in?
        flash[:danger] = "Merci de se connecter."
    	redirect_to login_url
      end


      def bon_utilisateur
        @utilisateur = Utilisateur.find(params[:id])
        redirect_to(root_url) unless @utilisateur == @utilisateur_courant
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(utilisateur)
    session[:utilisateur_id] = utilisateur.id
  end

  def utilisateur_courant
    @utilisateur_courant = @utilisateur_courant || Utilisateur.find_by(id: session[:utilisateur_id])
  end


  def logged_in?
    !utilisateur_courant.nil?
  end

  def log_out
    session.delete(:utilisateur_id)
    @utilisateur_courant = nil
  end
end

app/helpers/utilisateurs_helper.rb
module UtilisateursHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
            Copyright &copy; <a href="https://ensa.uit.ac.ma/">Ecole Nationales Des Scienes Appliquées, Kénitra, Maroc.</a>
        </small>
    </footer>
    <nav>
        <ul>
            <li><%= link_to "Contact", contact_path %></i>
            <li><%= link_to "Aide", aide_path %></i>
        </ul>
    </nav>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
  	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
    	<span class="sr-only">Toggle navigation</span>
    	<span class="icon-bar"></span>
    	<span class="icon-bar"></span>
    	<span class="icon-bar"></span>
  	</button>
  	<a class="navbar-brand" id="logo"  href="/">Le Blog</a>
	</div>

	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  	<ul class="nav navbar-nav">
    	<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
    	<li><a href="#">Link</a></li>
    	<li class="dropdown">
      	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
      	<ul class="dropdown-menu">
        	<li><a href="#">Action</a></li>
        	<li><a href="#">Another action</a></li>
        	<li><a href="#">Something else here</a></li>
        	<li role="separator" class="divider"></li>
        	<li><a href="#">Separated link</a></li>
        	<li role="separator" class="divider"></li>
        	<li><a href="#">One more separated link</a></li>
      	</ul>
    	</li>
  	</ul>
  	<form class="navbar-form navbar-left">
    	<div class="form-group">
      	<input type="text" class="form-control" placeholder="Search">
    	</div>
    	<button type="submit" class="btn btn-default">Submit</button>
  	</form>
  	<ul class="nav navbar-nav navbar-right">

    	<% if logged_in? %>

      	<li><%= link_to "Utilisateurs",	utilisateurs_path %></li>
      	<li class="dropdown">
        	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Compte <span class="caret"></span></a>

          	<ul class="dropdown-menu">
            	<li><%= link_to "Profile", utilisateur_path(utilisateur_courant) %></li>
            	<li><%= link_to "Paramètres", edit_utilisateur_path(utilisateur_courant) %></li>
            	<li role="separator" class="divider"></li>
            	<li><%= link_to "Se déconnecter", logout_path, method: "delete" %></li>
          	</ul>
      	</li>

    	<% else %>
      	<li><%= link_to "Se connecter", login_path %></li>
    	<% end %>

  	</ul>
	</div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @titre %> | Mon App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">



  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <% flash.each do |message_type, messgae| %>
      <div class="alert alert-<%= message_type %>"><%= messgae%></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/aide.html.erb
<h1> Page : Aide</h1>
<p>Bonjour</p>

app/views/pages/contact.html.erb
<h1> Page : Contact</h1>
<p>Bonjour</p>

app/views/pages/home.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="jumbotron">
        <h1>LE BLOG</h1>
        <p>Un blog est un type de site web - ou une partie d'un site web - utilisé pour la publication périodique et régulière d'articles, généralement succincts, et rendant compte d'une actualité autour d'un sujet donné ou d'une profession. (<a href ="https://fr.wikipedia.org/wiki/Blog">Wikipedia</a></a>)</p>
        <%= link_to "s'inscricre", inscription_path, class: "btn btn-lg btn-primary" %>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @utilisateur.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@utilisateur.errors.count, "error") %>.
	</div>
	<ul>
    <% @utilisateur.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/utilisateurs/edit.html.erb
<h1>Actualisation</h1>
    <%= form_for(@utilisateur, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <%= render 'shared/error_messages' %>
        	  <div class="form-group">
        		<div class="col-sm-2 control-label">
        		  <%= f.label :nom %>
        		</div>
        		<div class="col-sm-4">
        	  	<%= f.text_field :nom, class:"form-control",  placeholder:"Entrer votre nom"%>
        		</div>
        	  </div>

        	  <div class="form-group">
        		<div class="col-sm-2 control-label">
        		  <%= f.label :email %>
        		</div>
        		<div class="col-sm-4">
        	  	<%= f.email_field :email, class:"form-control",  placeholder:"Entrer votre email"%>
        		</div>
        	  </div>

        	  <div class="form-group">
        		<div class="col-sm-2 control-label">
        		  <%= f.label :password %>
        		</div>
        		<div class="col-sm-4">
        	  	<%= f.password_field :password , class:"form-control",  placeholder:"Entrer votre password"%>
        		</div>
        	  </div>

        	  <div class="form-group">
        		<div class="col-sm-2 control-label">
        		  <%= f.label :password_confirmation, "Confirmation"  %>
        		</div>
        		<div class="col-sm-4">
        	  	<%= f.password_field :password_confirmation, class:"form-control",  placeholder:"Entrer votre password"%>
        		</div>
        	  </div>

        	  <div class="form-group">
        		<div class="col-sm-offset-2 col-sm-4">
        	  	<%= f.submit "Actualiser", class: "btn btn-primary" %>
        		</div>
        	  </div>

    <% end %>

app/views/utilisateurs/index.html.erb
<h1>Tous les utilisateurs</h1>

<ul class="utilisateurs">
  <% @utilisateurs.each do |utilisateur| %>
	<li>
    	<%= link_to utilisateur.nom, utilisateur %>

    	<% if @utilisateur_courant.admin? || utilisateur_courant == utilisateur  %>
	|     <%= link_to "delete", utilisateur, method: :delete,
                              	data: { confirm: "confirmer" } %>
        <% end %>

	</li>
  <% end %>
</ul>

app/views/utilisateurs/new.html.erb
<h1>Inscription</h1>


	<%= form_for(@utilisateur, :html => {class: "form-horizontal", role: "form"}) do |f| %>

            <%= render 'shared/error_messages'%>

        	  <div class="form-group">
        	    <div class="col-sm-2 control-label">
        	      <%= f.label :nom %>
        	    </div>
        	    <div class="col-sm-4">
        	      <%= f.text_field :nom, class:"form-control",  placeholder:"Entrer votre nom"%>
        	    </div>
        	  </div>

        	  <div class="form-group">
        	    <div class="col-sm-2 control-label">
        	      <%= f.label :email %>
        	    </div>
        	    <div class="col-sm-4">
        	      <%= f.email_field :email, class:"form-control",  placeholder:"Entrer votre email"%>
        	    </div>
        	  </div>

        	  <div class="form-group">
  	  		<div class="col-sm-2 control-label">
        	      <%= f.label :password %>
        	    </div>
        	    <div class="col-sm-4">
        	      <%= f.password_field :password , class:"form-control",  placeholder:"Entrer votre password"%>
        	    </div>
        	  </div>

        	  <div class="form-group">
        	    <div class="col-sm-2 control-label">
        	      <%= f.label :password_confirmation, "Confirmation"  %>
        	    </div>
        	    <div class="col-sm-4">
        	      <%= f.password_field :password_confirmation, class:"form-control",  placeholder:"Entrer votre password"%>
        	    </div>
        	  </div>

        	  <div class="form-group">
        	    <div class="col-sm-offset-2 col-sm-4">
        	      <%= f.submit "Creer", class: "btn btn-primary" %>
        	    </div>
        	  </div>

	<% end %>

app/views/utilisateurs/show.html.erb
<%= @utilisateur.nom %>, <%= @utilisateur.email %>